export const ROUTINES_GET_LIST_REQUEST = 'ROUTINES_GET_LIST_REQUEST';
export const ROUTINES_GET_LIST_SUCCESS = 'ROUTINES_GET_LIST_SUCCESS';
export const ROUTINES_GET_LIST_ERROR = 'ROUTINES_GET_LIST_ERROR';

export const ROUTINES_CREATE_REQUEST = 'ROUTINES_CREATE_REQUEST';
export const ROUTINES_CREATE_SUCCESS = 'ROUTINES_CREATE_SUCCESS';
export const ROUTINES_CREATE_ERROR = 'ROUTINES_CREATE_ERROR';

export const ASANAS_GET_LIST_REQUEST = 'ASANAS_GET_LIST_REQUEST';
export const ASANAS_GET_LIST_SUCCESS = 'ASANAS_GET_LIST_SUCCESS';
export const ASANAS_GET_LIST_ERROR = 'ASANAS_GET_LIST_ERROR';

export const ASANAS_CREATE_REQUEST = 'ASANAS_CREATE_REQUEST';
export const ASANAS_CREATE_SUCCESS = 'ASANAS_CREATE_SUCCESS';
export const ASANAS_CREATE_ERROR = 'ASANAS_CREATE_ERROR';